In [2]:
import pandas as pd
import numpy as np

In [3]:
markers_df = pd.read_csv("lifu_markers_1_2back_-1580742246.csv")
calibration_complete =markers_df[markers_df["marker"] == "START_EXPERIMENT_RECEIVED"].iloc[-1]
calibration_complete = calibration_complete["LSL_timestamp"]
markers_df_on = markers_df[markers_df["marker"] =="LIFU_ON"]
markers_df

          Time               marker  LSL_timestamp
0     3.637320  collecting_baseline   1.783423e+06
1     3.667621  collecting_baseline   1.783423e+06
2     3.699527  collecting_baseline   1.783423e+06
3     3.758207  collecting_baseline   1.783423e+06
4     3.776974  collecting_baseline   1.783424e+06
..         ...                  ...            ...
206  55.484377              LIFU_ON   1.783475e+06
207  60.848151             LIFU_OFF   1.783481e+06
208  62.940774              LIFU_ON   1.783483e+06
209  68.294516             LIFU_OFF   1.783488e+06
210  73.289191              LIFU_ON   1.783493e+06

[211 rows x 3 columns]

In [4]:
calibration_complete

1783460.5785901

In [5]:
eeg_df = pd.read_csv("eeg_LSL_gpype2back_-1580742246.csv")
eeg_df

,Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06
0,1.783421e+06,-200000.000000,-89.982712,8096.888184,193.381714,45.708546,1.912842e+07
1,1.783421e+06,-200000.000000,-182.449097,33287.675781,859.135254,204.979706,5.934101e+07
2,1.783421e+06,-200000.000000,-327.047363,106959.976562,2998.334717,716.749878,8.385208e+07
3,1.783421e+06,-200000.000000,-533.366211,284479.500000,8687.924805,2077.895996,1.220201e+08
4,1.783421e+06,-200000.000000,-807.421692,651929.812500,21726.521484,5197.177246,1.635951e+08
...,...,...,...,...,...,...,...
18277,1.783494e+06,-18098.712891,10.230962,104.672585,27.585535,6.044386,5.406032e+00
18278,1.783494e+06,-18878.390625,10.831090,117.312500,29.431763,6.486068,5.406032e+00
18279,1.783494e+06,-18624.996094,11.269844,127.009384,31.549963,6.992815,5.406032e+00
18280,1.783495e+06,0.000000,11.561377,133.665451,33.878471,7.549873,5.406032e+00
18281,1.783495e+06,-5978.584961,1.381549,1.908678,9.320990,1.674878,1.099407e+00

In [6]:
eeg_df = eeg_df.rename(columns = {"Time": "LSL Time", "Ch01": "Raw", "Ch02": "Theta Bandpass", "Ch03": "Power", "Ch04": "Moving Average", "Ch05": "Z-score", "Ch06": "Hold"})
eeg_df

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold
0,1.783421e+06,-200000.000000,-89.982712,8096.888184,193.381714,45.708546,1.912842e+07
1,1.783421e+06,-200000.000000,-182.449097,33287.675781,859.135254,204.979706,5.934101e+07
2,1.783421e+06,-200000.000000,-327.047363,106959.976562,2998.334717,716.749878,8.385208e+07
3,1.783421e+06,-200000.000000,-533.366211,284479.500000,8687.924805,2077.895996,1.220201e+08
4,1.783421e+06,-200000.000000,-807.421692,651929.812500,21726.521484,5197.177246,1.635951e+08
...,...,...,...,...,...,...,...
18277,1.783494e+06,-18098.712891,10.230962,104.672585,27.585535,6.044386,5.406032e+00
18278,1.783494e+06,-18878.390625,10.831090,117.312500,29.431763,6.486068,5.406032e+00
18279,1.783494e+06,-18624.996094,11.269844,127.009384,31.549963,6.992815,5.406032e+00
18280,1.783495e+06,0.000000,11.561377,133.665451,33.878471,7.549873,5.406032e+00
18281,1.783495e+06,-5978.584961,1.381549,1.908678,9.320990,1.674878,1.099407e+00

In [7]:
lifu_on = markers_df[markers_df["marker"]=="LIFU_ON"].copy()
lifu_on_timestamp = lifu_on["LSL_timestamp"]
lifu_on_timestamp = np.array(lifu_on_timestamp)
lifu_on_timestamp

array([1783460.6038521, 1783467.9537836, 1783475.2202884, 1783482.676686 ,
       1783493.0251028])

In [33]:
target_ts = lifu_on_timestamp

tol = 1e-2  # tolerance for float comparison

df_matches = eeg_df[
    eeg_df["LSL Time"].apply(
        lambda x: np.any(np.abs(target_ts - x) < tol)
    )
]

df_matches

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,offline z-score,LIFU
10027,1.783461e+06,-3694.606201,-1.072812,1.150926,8.718289,1.530691,1.629042,1.629042,0.0
10028,1.783461e+06,-2815.175293,-0.896502,0.803715,8.381421,1.450101,1.629042,1.629042,0.0
10029,1.783461e+06,-2265.811279,-0.718098,0.515665,7.967010,1.350959,1.629042,1.629042,0.0
11846,1.783468e+06,-4490.495117,1.114894,1.242988,87.348351,20.341711,21.166565,NaN,0.0
11847,1.783468e+06,-3643.608643,-0.390538,0.152520,83.067123,19.317495,21.166565,NaN,0.0
11848,1.783468e+06,-3935.432861,-1.843343,3.397915,78.271996,18.170334,13.061582,NaN,0.0
13663,1.783475e+06,-5318.142090,-2.839474,8.062614,9.084822,1.618378,1.833443,1.833443,0.0
13664,1.783475e+06,-4435.897461,-2.810031,7.896275,8.798126,1.549791,1.833443,1.833443,0.0
13665,1.783475e+06,-4678.631348,-2.732394,7.465977,8.485684,1.475044,1.475044,1.475044,0.0
15486,1.783483e+06,-5265.999023,1.754079,3.076794,70.392273,16.285233,17.080481,NaN,0.0
15487,1.783483e+06,-6209.970215,1.764757,3.114368,67.911095,15.691648,17.080481,NaN,0.0
15488,1.783483e+06,-6363.940430,1.563228,2.443681,66.197678,15.281741,17.080481,NaN,0.0
18092,1.783493e+06,-16340.471680,6.857118,47.020069,131.915329,31.003668,58.187683,NaN,0.0
18093,1.783493e+06,-16004.539062,6.578590,43.277851,121.467506,28.504190,58.187683,NaN,0.0
18094,1.783493e+06,-16603.068359,6.232359,38.842304,113.132935,26.510269,25.006388,NaN,0.0
18095,1.783493e+06,-17228.962891,5.830214,33.991394,106.846703,25.006388,25.006388,NaN,0.0
18096,1.783493e+06,-16507.125000,5.384183,28.989431,102.437355,23.951519,25.006388,NaN,0.0
18097,1.783493e+06,-16019.750000,4.905993,24.068768,99.645836,23.283691,25.006388,NaN,0.0

In [34]:
lifu_on_timestamp[-1]

1783493.0251028

In [35]:
merged_df = eeg_df

In [36]:
buffer = []
offline_z = []
last_theta_val = None

MU = 2.32
SIGMA = 4.18
MAD_THRESHOLD = 6
THETA_THRESHOLD_Z = 1.5
INITIAL_CUTOFF = 100.0
BUFFER_SIZE = 500
COOLDOWN_TIME = 7
sonication_enabled = calibration_complete

# Ch05 = index 4
channel = "Hold"

for i in range(len(merged_df)):

    theta_val = merged_df[channel].iloc[i]   # MUST match online
    if last_theta_val is not None and theta_val == last_theta_val:
        offline_z.append(last_theta_val) 
        continue
    # Warm-up
    if len(buffer) <= 200:
        if theta_val < INITIAL_CUTOFF:
            buffer.append(theta_val)
        offline_z.append(np.nan)
        continue

    # Rolling buffer
    if len(buffer) > BUFFER_SIZE:
        buffer.pop(0)

    arr = np.array(buffer)
    median = np.median(arr)
    mad = np.median(np.abs(arr - median)) + 1e-6

    # Artifact rejection
    z_art = abs(theta_val - median) / mad
    if z_art > MAD_THRESHOLD:
        offline_z.append(np.nan)
        continue

    # Clean sample
    buffer.append(theta_val)
    last_theta_val = theta_val

    # Z-score
    offline_z.append(theta_val)

merged_df["offline z-score"] = offline_z

In [37]:
LIFU = np.zeros(len(merged_df))
last_trigger_time = -999

for i in range(len(merged_df)):
    theta_z = merged_df["offline z-score"].iloc[i]
    now = merged_df["LSL Time"].iloc[i]

    if now> sonication_enabled and theta_z > THETA_THRESHOLD_Z and theta_z < MAD_THRESHOLD and (now - last_trigger_time > COOLDOWN_TIME):
        LIFU[i] = 1.0
        last_trigger_time = now

In [38]:
merged_df["LIFU"] = LIFU
merged_df

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,offline z-score,LIFU
0,1.783421e+06,-200000.000000,-89.982712,8096.888184,193.381714,45.708546,1.912842e+07,NaN,0.0
1,1.783421e+06,-200000.000000,-182.449097,33287.675781,859.135254,204.979706,5.934101e+07,NaN,0.0
2,1.783421e+06,-200000.000000,-327.047363,106959.976562,2998.334717,716.749878,8.385208e+07,NaN,0.0
3,1.783421e+06,-200000.000000,-533.366211,284479.500000,8687.924805,2077.895996,1.220201e+08,NaN,0.0
4,1.783421e+06,-200000.000000,-807.421692,651929.812500,21726.521484,5197.177246,1.635951e+08,NaN,0.0
...,...,...,...,...,...,...,...,...,...
18277,1.783494e+06,-18098.712891,10.230962,104.672585,27.585535,6.044386,5.406032e+00,NaN,0.0
18278,1.783494e+06,-18878.390625,10.831090,117.312500,29.431763,6.486068,5.406032e+00,NaN,0.0
18279,1.783494e+06,-18624.996094,11.269844,127.009384,31.549963,6.992815,5.406032e+00,NaN,0.0
18280,1.783495e+06,0.000000,11.561377,133.665451,33.878471,7.549873,5.406032e+00,NaN,0.0
18281,1.783495e+06,-5978.584961,1.381549,1.908678,9.320990,1.674878,1.099407e+00,1.099407,0.0

In [39]:
mask_lifu = merged_df["LIFU"] == 1.0
lifu_on = merged_df[mask_lifu]
lifu_on["LSL Time"] = lifu_on["LSL Time"]
lifu_on_cal = lifu_on[lifu_on["LSL Time"] > calibration_complete]
lifu_on_cal

C:\Users\jshin\AppData\Local\Temp\ipykernel_15156\10077578.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lifu_on["LSL Time"] = lifu_on["LSL Time"]

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,offline z-score,LIFU
10025,1.783461e+06,-2304.411377,-1.411807,1.993198,9.129397,1.629042,1.629042,1.629042,1.0
11895,1.783468e+06,-5066.657715,-3.426513,11.740993,19.847549,4.193194,4.193194,4.193194,1.0
13636,1.783475e+06,-4808.640625,3.809649,14.513423,9.223145,1.651470,1.613923,1.613923,1.0
15506,1.783483e+06,-5262.088867,-1.473139,2.170138,27.080816,5.923640,1.993296,1.993296,1.0
18133,1.783493e+06,-17260.099609,-2.965671,8.795202,13.560341,2.689077,2.480923,2.480923,1.0

In [40]:
here = lifu_on_cal.iloc[0]
here['LSL Time']

1783460.5787968

In [41]:
lifu_on_time = lifu_on_cal["LSL Time"]
lifu_on_time = np.array(lifu_on_time)
lifu_on_final = lifu_on_time

In [42]:
lifu_on_final - target_ts

array([-0.0250553,  0.1629646, -0.0990257,  0.0941191,  0.1567006])

In [43]:
lifu_on_time

array([1783460.5787968, 1783468.1167482, 1783475.1212627, 1783482.7708051,
       1783493.1818034])

In [44]:
target_ts

array([1783460.6038521, 1783467.9537836, 1783475.2202884, 1783482.676686 ,
       1783493.0251028])

In [46]:
start_time = eeg_df['LSL Time'].iloc[0]
target_ts_onset = target_ts - start_time
target_ts_onset

array([40.0833693, 47.4333008, 54.6998056, 62.1562032, 72.50462  ])

In [47]:
calibration_complete

1783460.5785901