In [93]:
import pandas as pd
import numpy as np
import os

In [94]:
markers_df = pd.read_csv("lifu_markers_1_2back_use.csv")
calibration_complete =markers_df[markers_df["marker"] == "START_EXPERIMENT_RECEIVED"].iloc[-1]
calibration_complete = calibration_complete["LSL_timestamp"]
markers_df_on = markers_df[markers_df["marker"] =="LIFU_ON"]
markers_df

          Time               marker  LSL_timestamp
0     3.321529  collecting_baseline  471418.389361
1     3.380793  collecting_baseline  471418.448625
2     3.423872  collecting_baseline  471418.491704
3     3.460233  collecting_baseline  471418.528065
4     3.491563  collecting_baseline  471418.559395
..         ...                  ...            ...
207  43.839331             LIFU_OFF  471458.907163
208  46.837734              LIFU_ON  471461.905567
209  51.838728             LIFU_OFF  471466.906560
210  54.830428              LIFU_ON  471469.898260
211  59.840959             LIFU_OFF  471474.908791

[212 rows x 3 columns]

In [95]:
calibration_complete # remove 0 w actual marker time

471435.3551405

In [98]:
eeg_df = pd.read_csv("scope_eeg_2back_use.csv")
eeg_df

,Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07
0,471416.210218,68495.437500,-5481.288086,3.004452e+07,8.015223e+07,1.917517e+07,1.174412e+07,19.380829
1,471416.217459,67077.734375,-6034.888184,3.641987e+07,7.975186e+07,1.907939e+07,1.174412e+07,20.559973
2,471416.219522,66970.476562,-6461.399902,4.174969e+07,7.896676e+07,1.889157e+07,1.174412e+07,21.697979
3,471416.224276,68426.023438,-6762.174316,4.572700e+07,7.774569e+07,1.859945e+07,1.174412e+07,22.856195
4,471416.228121,68615.609375,-6941.034180,4.817795e+07,7.607249e+07,1.819916e+07,1.174412e+07,24.033749
...,...,...,...,...,...,...,...,...
14891,471476.742069,63369.832031,-77.437767,5.996608e+03,1.076966e+04,2.575919e+03,2.585887e+03,-0.450851
14892,471476.747148,65477.355469,-59.074207,3.489762e+03,1.066901e+04,2.551840e+03,2.585887e+03,-0.453871
14893,471476.755364,63089.562500,-39.906792,1.592552e+03,1.056460e+04,2.526861e+03,2.585887e+03,-0.436750
14894,471476.759171,61256.148438,-20.298996,4.120492e+02,1.047259e+04,2.504850e+03,2.585887e+03,-0.408417
14895,471476.760935,62766.824219,-0.616498,3.800692e-01,1.040693e+04,2.489142e+03,2.585887e+03,-0.338639

In [99]:
eeg_df = eeg_df.rename(columns = {"Time": "LSL Time", "Ch01": "Raw", "Ch02": "Theta Bandpass", "Ch03": "Power", "Ch04": "Moving Average", "Ch05": "Z-score", "Ch06": "Hold", "Ch07": "Trigger Channel"})
eeg_df

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel
0,471416.210218,68495.437500,-5481.288086,3.004452e+07,8.015223e+07,1.917517e+07,1.174412e+07,19.380829
1,471416.217459,67077.734375,-6034.888184,3.641987e+07,7.975186e+07,1.907939e+07,1.174412e+07,20.559973
2,471416.219522,66970.476562,-6461.399902,4.174969e+07,7.896676e+07,1.889157e+07,1.174412e+07,21.697979
3,471416.224276,68426.023438,-6762.174316,4.572700e+07,7.774569e+07,1.859945e+07,1.174412e+07,22.856195
4,471416.228121,68615.609375,-6941.034180,4.817795e+07,7.607249e+07,1.819916e+07,1.174412e+07,24.033749
...,...,...,...,...,...,...,...,...
14891,471476.742069,63369.832031,-77.437767,5.996608e+03,1.076966e+04,2.575919e+03,2.585887e+03,-0.450851
14892,471476.747148,65477.355469,-59.074207,3.489762e+03,1.066901e+04,2.551840e+03,2.585887e+03,-0.453871
14893,471476.755364,63089.562500,-39.906792,1.592552e+03,1.056460e+04,2.526861e+03,2.585887e+03,-0.436750
14894,471476.759171,61256.148438,-20.298996,4.120492e+02,1.047259e+04,2.504850e+03,2.585887e+03,-0.408417
14895,471476.760935,62766.824219,-0.616498,3.800692e-01,1.040693e+04,2.489142e+03,2.585887e+03,-0.338639

In [100]:
lifu_on = markers_df[markers_df["marker"]=="LIFU_ON"].copy()
lifu_on_timestamp = lifu_on["LSL_timestamp"]
lifu_on_timestamp = np.array(lifu_on_timestamp)
lifu_on_timestamp

array([471438.2709168, 471445.7642586, 471453.9033159, 471461.9055666,
       471469.8982602])

In [106]:
target_ts = lifu_on_timestamp

tol = 3e-3  # tolerance for float comparison

df_matches = eeg_df[
    eeg_df["LSL Time"].apply(
        lambda x: np.any(np.abs(target_ts - x) < tol)
    )
]

df_matches

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel
5489,471438.269441,65557.984375,-3.395509,11.529478,10.567862,1.973173,1.904089,-0.108388
5490,471438.273675,63376.218750,-2.807700,7.883182,10.575391,1.974974,1.904089,-0.140757
7320,471445.766522,65310.582031,-14.594992,213.013763,140.611252,33.084034,37.647846,0.235228
11268,471461.904997,65710.289062,-6.151478,37.840679,59.809776,13.753535,14.451962,0.040555
11269,471461.906717,63039.781250,-6.450948,41.614735,57.925556,13.302763,14.451962,0.129536
11270,471461.907872,62043.000000,-6.703480,44.936638,56.954296,13.070404,14.451962,0.169344
13228,471469.900665,61895.738281,-9.652644,93.173546,110.995766,25.998987,26.477091,0.103944

In [107]:
merged_df = eeg_df

In [108]:
buffer = []
offline_z = []
last_theta_val = None

MU = 2.32
SIGMA = 4.18
MAD_THRESHOLD = 60
THETA_THRESHOLD_Z = 1.5
INITIAL_CUTOFF = 100.0
BUFFER_SIZE = 500
COOLDOWN_TIME = 7
sonication_enabled = calibration_complete

# Ch05 = index 4
channel = "Hold"

for i in range(len(merged_df)):
    theta_val = merged_df[channel].iloc[i]   # MUST match online
    if last_theta_val is not None and theta_val == last_theta_val:
        offline_z.append(last_theta_val) 
        continue
    # Warm-up
    if len(buffer) <= 200:
        if theta_val < INITIAL_CUTOFF:
            buffer.append(theta_val)
        offline_z.append(np.nan)
        continue

    # Rolling buffer
    if len(buffer) > BUFFER_SIZE:
        buffer.pop(0)

    arr = np.array(buffer)
    median = np.median(arr)
    mad = np.median(np.abs(arr - median)) + 1e-6

    # Artifact rejection
    z_art = abs(theta_val - median) / mad
    if z_art > MAD_THRESHOLD:
        offline_z.append(np.nan)
        continue

    # Clean sample
    buffer.append(theta_val)
    last_theta_val = theta_val

    # Z-score
    offline_z.append(theta_val)

merged_df["offline z-score"] = offline_z

In [109]:
LIFU = np.zeros(len(merged_df))
last_trigger_time = -999

for i in range(len(merged_df)):
    theta_z = merged_df["offline z-score"].iloc[i]
    now = merged_df["LSL Time"].iloc[i]

    if now> sonication_enabled and theta_z > THETA_THRESHOLD_Z and theta_z < MAD_THRESHOLD and (now - last_trigger_time > COOLDOWN_TIME):
        LIFU[i] = 1.0
        last_trigger_time = now

In [110]:
merged_df["LIFU"] = LIFU
merged_df

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,LIFU
0,471416.210218,68495.437500,-5481.288086,3.004452e+07,8.015223e+07,1.917517e+07,1.174412e+07,19.380829,NaN,0.0
1,471416.217459,67077.734375,-6034.888184,3.641987e+07,7.975186e+07,1.907939e+07,1.174412e+07,20.559973,NaN,0.0
2,471416.219522,66970.476562,-6461.399902,4.174969e+07,7.896676e+07,1.889157e+07,1.174412e+07,21.697979,NaN,0.0
3,471416.224276,68426.023438,-6762.174316,4.572700e+07,7.774569e+07,1.859945e+07,1.174412e+07,22.856195,NaN,0.0
4,471416.228121,68615.609375,-6941.034180,4.817795e+07,7.607249e+07,1.819916e+07,1.174412e+07,24.033749,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...
14891,471476.742069,63369.832031,-77.437767,5.996608e+03,1.076966e+04,2.575919e+03,2.585887e+03,-0.450851,NaN,0.0
14892,471476.747148,65477.355469,-59.074207,3.489762e+03,1.066901e+04,2.551840e+03,2.585887e+03,-0.453871,NaN,0.0
14893,471476.755364,63089.562500,-39.906792,1.592552e+03,1.056460e+04,2.526861e+03,2.585887e+03,-0.436750,NaN,0.0
14894,471476.759171,61256.148438,-20.298996,4.120492e+02,1.047259e+04,2.504850e+03,2.585887e+03,-0.408417,NaN,0.0
14895,471476.760935,62766.824219,-0.616498,3.800692e-01,1.040693e+04,2.489142e+03,2.585887e+03,-0.338639,NaN,0.0

In [111]:
mask_lifu = merged_df["LIFU"] == 1.0
lifu_on_df = merged_df[mask_lifu]
lifu_on_df["LSL Time"] = lifu_on_df["LSL Time"]
lifu_on_cal = lifu_on_df[lifu_on_df["LSL Time"] > calibration_complete]
lifu_on_cal

C:\Users\jshin\AppData\Local\Temp\ipykernel_29368\4113107194.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lifu_on_df["LSL Time"] = lifu_on_df["LSL Time"]

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,LIFU
5487,471438.263319,65092.425781,-4.341425,18.847973,10.279091,1.904089,1.904089,0.183626,1.904089,1.0
7317,471445.757379,66541.312500,-8.791781,77.295410,159.687988,37.647846,37.647846,-0.063991,37.647846,1.0
9315,471453.886959,66077.546875,4.806467,23.102121,138.822830,32.656181,29.101910,-0.206477,29.101910,1.0
11266,471461.898937,62214.355469,-5.419933,29.375677,66.765076,15.417480,14.451962,-0.030073,14.451962,1.0
13227,471469.889457,62060.718750,-9.596001,92.083229,112.994240,26.477091,26.477091,0.131711,26.477091,1.0

In [112]:
lifu_on_time = lifu_on_cal["LSL Time"]
lifu_on_time = np.array(lifu_on_time)
offline_lifu= lifu_on_time

In [113]:
offline_lifu # because the begin calibration didn't start yet that's why it doesn't

array([471438.2633187, 471445.7573786, 471453.8869589, 471461.8989372,
       471469.8894567])

In [114]:
target_ts

array([471438.2709168, 471445.7642586, 471453.9033159, 471461.9055666,
       471469.8982602])

In [115]:
calibration_complete

471435.3551405

In [116]:
offline_lifu - target_ts

array([-0.0075981, -0.00688  , -0.016357 , -0.0066294, -0.0088035])

In [117]:
channel_8 = eeg_df.nlargest(5, "Trigger Channel")
channel_8 # calculate latency by time??

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,LIFU
32,471416.584268,68208.312500,2126.591309,4522390.50,27622230.0,6608188.0,3712639.500,40.774078,NaN,0.0
33,471416.588187,68649.726562,2279.087402,5194239.00,24906172.0,5958414.5,2038472.375,40.687012,NaN,0.0
31,471416.580761,66732.898438,1963.668335,3855993.25,30502668.0,7297288.0,3712639.500,40.671894,NaN,0.0
34,471416.590727,67666.710938,2422.100830,5866572.00,22439900.0,5368396.0,2038472.375,40.476147,NaN,0.0
30,471416.580046,67419.039062,1788.848633,3199979.50,33448272.0,8001978.5,3712639.500,40.437794,NaN,0.0

In [118]:
#windowing
raw_with08 = pd.read_csv("thetaEEG_full_2back_nogui.csv")
raw = raw_with08.drop(' Ch08', axis = 1)
pre = 2
post = 5
windows = []
target_ts_onset = np.array(lifu_on['Time'])


for idx, event in enumerate(target_ts_onset): 
    mask = (raw['Time'] >= (event - pre)) & (raw['Time'] <= (event + post))
    window_df = raw.loc[mask].copy()
    window_df["t_rel"] = window_df["Time"] - event 
    window_df["idx"] = idx
    windows.append(window_df)
windows[0]

,Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07,t_rel,idx
5301,21.204,199999.96875,199999.96875,199999.96875,199999.96875,316.977539,199999.96875,186865.421875,-1.999085,0
5302,21.208,199999.96875,199999.96875,199999.96875,199999.96875,320.053131,199999.96875,186120.078125,-1.995085,0
5303,21.212,199999.96875,199999.96875,199999.96875,199999.96875,317.502045,199999.96875,186694.921875,-1.991085,0
5304,21.216,199999.96875,199999.96875,199999.96875,199999.96875,316.882172,199999.96875,187467.453125,-1.987085,0
5305,21.220,199999.96875,199999.96875,199999.96875,199999.96875,315.761627,199999.96875,187015.625000,-1.983085,0
...,...,...,...,...,...,...,...,...,...,...
7046,28.184,199999.96875,199999.96875,199999.96875,199999.96875,291.633636,199999.96875,685.119629,4.980915,0
7047,28.188,199999.96875,199999.96875,199999.96875,199999.96875,385.093689,199999.96875,-73.337563,4.984915,0
7048,28.192,199999.96875,199999.96875,199999.96875,199999.96875,402.712830,199999.96875,-59.700012,4.988915,0
7049,28.196,199999.96875,199999.96875,199999.96875,199999.96875,314.307281,199999.96875,713.920715,4.992915,0
7050,28.200,199999.96875,199999.96875,199999.96875,199999.96875,289.082520,199999.96875,753.927246,4.996915,0

In [119]:
base_dir = r"C:\Users\jshin\OW_closedloopLIFU\eeg_windows"
# MAKE SURE TO PUT IN NAME
new_folder_name = "demo_1129"
new_folder_path = os.path.join(base_dir, new_folder_name)
os.makedirs(new_folder_path, exist_ok=False) # check

for idx, event in enumerate(target_ts_onset):
    # Build a unique filename for each event
    output_path = os.path.join(new_folder_path, f"{idx}_{event}_eeg.csv")
    try:
        windows[idx].to_csv(output_path, index=False, encoding="utf-8")
        print(f"Saved successfully to: {output_path}")
    except (OSError, IOError) as e:
        print(f"Error saving CSV file: {e}")

Saved successfully to: C:\Users\jshin\OW_closedloopLIFU\eeg_windows\demo_1129\0_23.20308460004162_eeg.csv
Saved successfully to: C:\Users\jshin\OW_closedloopLIFU\eeg_windows\demo_1129\1_30.696426400041677_eeg.csv
Saved successfully to: C:\Users\jshin\OW_closedloopLIFU\eeg_windows\demo_1129\2_38.835483700037_eeg.csv
Saved successfully to: C:\Users\jshin\OW_closedloopLIFU\eeg_windows\demo_1129\3_46.83773440000368_eeg.csv
Saved successfully to: C:\Users\jshin\OW_closedloopLIFU\eeg_windows\demo_1129\4_54.83042800001567_eeg.csv